### ISSUE TITLE
Getting 0x5200007d error occasionally

### ISSUE THREAD

**Issue by punawije** [awslabs/amazon-kinesis-video-streams-producer-c#123] opened 2020-10-19 17:51 UTC
Calls to "putKinesisVideoFrame" hits 0x5200007d error callback intermittently. What are the conditions that gives this error? Description says "Frames missing for a track" but when I print out the sequence numbers for the Video and Audio tracks, there are no missing ones. I can get it to fail more often when I try to print out more debug info. Does this mean there is a timing requirement for this call? Please provide any info that can help me track down and fix this issue. Thank you!

I am using "cproducer" in KVS SDK version 2.01.

**Comment by MushMal** [comment] 2020-10-19 18:12
The definition of this status code is here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L174

This is a current limitation from our backend indicating that each fragment should have frames from each of the tracks. For example, if you have defined audio and video tracks, then each fragment should contain at least one frame from each of the tracks.

This could happen if one of the media pipelines (audio pipeline) could get stalled and doesn't produce audio frame for a certain duration.


Please check your media pipeline and ensure that audio encoder doesn't have "stutter". Try to increase video key-frame interval to 4 seconds.

**Comment by punawije** [comment] 2020-10-20 15:20
@MushMal, I am sending a key-frame every 1 second. I am also sending about two Audio frames per every Video frame sent. I don't see any audio "stutter." Following is a log output when the error happened. Please see if you can make out anything from that log, or let me know if I can provide any other log output that will help you determine the cause. Thank you!

```
[INFO]: [20/10-07:59:48.106]Sending I Frame
[INFO]: [20/10-07:59:48.430]Video seq: 7351  time [1603205984][671920]  len: 86808
[INFO]: [20/10-07:59:48.432]Audio seq: 12384  time [1603205984][709644]  len: 320
[INFO]: [20/10-07:59:48.478]Video seq: 7352  time [1603205984][735709]  len: 6635
[INFO]: [20/10-07:59:48.479]Audio seq: 12385  time [1603205984][745589]  len: 320
[INFO]: [20/10-07:59:48.480]Audio seq: 12386  time [1603205984][785592]  len: 320
[ERROR]: [20/10-07:59:48.495]Reported streamError callback for stream handle 9833261. Upload handle 0. Fragment timecode in 100ns: 16032059826720000. Error status: 0x5200007d
[ERROR]: [20/10-07:59:48.495]Reported streamError callback for stream handle 9833261. Upload handle 0. Fragment timecode in 100ns: 16032059826720000. Error status: 0x5200007d

2020-10-20 14:59:48 getStreamingTokenResult(): lala current time 16032059884957047, expiration 16032083763206847[INFO]: [20/10-07:59:48.507][KVS_APP]Video seq: 7353  time [1603205984][804808]  len: 4549
[INFO]: [20/10-07:59:48.509]Audio seq: 12387  time [1603205984][825634]  len: 320
[INFO]: [20/10-07:59:48.510]Audio seq: 12388  time [1603205984][865660]  len: 320
[INFO]: [20/10-07:59:48.510]Video seq: 7354  time [1603205984][868778]  len: 3423
[INFO]: [20/10-07:59:48.510]Audio seq: 12389  time [1603205984][911016]  len: 320
```

**Comment by MushMal** [comment] 2020-10-20 18:08
With the frame order coordinator we can reorder audio frames in order to make the overall frames monotonically increasing which is a requirement. Looking at the timestamps I am not sure what's what. Recommend you dumping the pts and dts for the frames and look for

1) Ensure you have the multi-track frame order coordinator mode selected (which I believe you do)
2) Ensure you have a key frame fragmentation set
3) Whether you have audio and video frames properly inlined
4) Check for video frames I-frame and ensure there are audio frames within the I-frames
5) Make sure your putFrame API call doesn't fail

**Comment by staowyze** [comment] 2020-10-27 17:03
here is a debug log with 0x5200007d error, from the log, are you able to tell if the a track is missing? thank you!
```
[2020-09-27 09:55:25] [KVS]putStreamCurlHandler(): Network thread for Kinesis Video stream: b0ee5507ef4d31b1f778e95f3b9b65c67ed26fec7b86a4531e2d8da17ad1260e with upload handle: 4 exited. http status: 0
[2020-09-27 09:55:25] [KVS]putStreamCurlHandler(): Stream with streamHandle 11943984 has exited without triggering end-of-stream. Service call result: 599
[2020-09-27 09:55:25] [KVS]kinesisVideoStreamTerminated(): Stream 0xb64030 terminated upload handle 4 with service call result 599.
[2020-09-27 09:55:25] [KVS]stepStateMachine(): State Machine - Current state: 0x0000000000000100, Next state: 0x0000000000000200
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 480000 bytes 5897 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 480000. Bytes available: 5897
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179070193970, dts: 16038179070193970, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 650000 bytes 16633 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 650000. Bytes available: 16633
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179070602700, dts: 16038179070602700, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179070632270, dts: 16038179070632270, duration: 0, size: 5426, trackId: 1, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 810000 bytes 16966 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 810000. Bytes available: 16966
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 1220000 bytes 17299 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 1220000. Bytes available: 17299
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179071197420, dts: 16038179071197420, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 1250000 bytes 22738 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 1250000. Bytes available: 22738
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179071373550, dts: 16038179071373550, duration: 0, size: 3503, trackId: 1, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 1810000 bytes 23071 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 1810000. Bytes available: 23071
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179071413120, dts: 16038179071413120, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 1990000 bytes 26587 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 1990000. Bytes available: 26587
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179071852010, dts: 16038179071852010, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179072025350, dts: 16038179072025350, duration: 0, size: 6941, trackId: 1, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 2030000 bytes 26920 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 2030000. Bytes available: 26920
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 2470000 bytes 27253 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 2470000. Bytes available: 27253
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179072203150, dts: 16038179072203150, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 2640000 bytes 34207 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 2640000. Bytes available: 34207
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179072604730, dts: 16038179072604730, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179072654990, dts: 16038179072654990, duration: 0, size: 3864, trackId: 1, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 2820000 bytes 34540 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 2820000. Bytes available: 34540
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 3220000 bytes 34873 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 3220000. Bytes available: 34873
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179073188830, dts: 16038179073188830, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 3270000 bytes 38750 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 3270000. Bytes available: 38750
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179073358870, dts: 16038179073358870, duration: 0, size: 3974, trackId: 1, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 3800000 bytes 39083 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 3800000. Bytes available: 39083
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179073411810, dts: 16038179073411810, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 3970000 bytes 43070 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 3970000. Bytes available: 43070
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179073867390, dts: 16038179073867390, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:30] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179074010830, dts: 16038179074010830, duration: 0, size: 4122, trackId: 1, isKey 0
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 4030000 bytes 43403 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 4030000. Bytes available: 43403
[2020-09-27 09:58:30] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 4480000 bytes 43736 for stream handle 5
[2020-09-27 09:58:30] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 4480000. Bytes available: 43736
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 12950000 bytes 178002 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 12950000. Bytes available: 178002
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179089417390, dts: 16038179089417390, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 13190000 bytes 183769 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 13190000. Bytes available: 183769
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179089867390, dts: 16038179089867390, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179090040800, dts: 16038179090040800, duration: 0, size: 4247, trackId: 1, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 13220000 bytes 184102 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 13220000. Bytes available: 184102
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 13670000 bytes 184435 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 13670000. Bytes available: 184435
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179090210620, dts: 16038179090210620, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 13850000 bytes 188695 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 13850000. Bytes available: 188695
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179090612800, dts: 16038179090612800, duration: 0, size: 5174, trackId: 1, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 14020000 bytes 189028 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 14020000. Bytes available: 189028
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179090621630, dts: 16038179090621630, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 14420000 bytes 194215 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 14420000. Bytes available: 194215
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179091193840, dts: 16038179091193840, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179091413280, dts: 16038179091413280, duration: 0, size: 2804, trackId: 1, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 14430000 bytes 194548 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 14430000. Bytes available: 194548
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 15000000 bytes 194881 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 15000000. Bytes available: 194881
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179091438120, dts: 16038179091438120, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 15220000 bytes 197698 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 15220000. Bytes available: 197698
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179091852020, dts: 16038179091852020, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179092009150, dts: 16038179092009150, duration: 0, size: 7024, trackId: 1, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 15240000 bytes 198031 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 15240000. Bytes available: 198031
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 15660000 bytes 198364 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 15660000. Bytes available: 198364
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179092202910, dts: 16038179092202910, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 15810000 bytes 205401 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 15810000. Bytes available: 205401
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179092605650, dts: 16038179092605650, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179092659480, dts: 16038179092659480, duration: 0, size: 6064, trackId: 1, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 16010000 bytes 205734 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 16010000. Bytes available: 205734
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 16410000 bytes 206067 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 16410000. Bytes available: 206067
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179093188170, dts: 16038179093188170, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 16460000 bytes 212144 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 16460000. Bytes available: 212144
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179093411800, dts: 16038179093411800, duration: 0, size: 5874, trackId: 1, isKey 0
[2020-09-27 09:58:31] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 16990000 bytes 212477 for stream handle 5
[2020-09-27 09:58:31] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 5. Duration available in 100ns: 16990000. Bytes available: 212477
[2020-09-27 09:58:31] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179093416040, dts: 16038179093416040, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 24170000 bytes 244808 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 24170000. Bytes available: 244808
[2020-09-27 09:58:32] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179113829630, dts: 16038179113829630, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:32] [KVS]writeHeaderCallback(): RequestId: d44b8729-67c5-638d-8c59-d4d1806086ba
[2020-09-27 09:58:32] [KVS]postReadCallback(): postBodyStreamingReadFunc (curl callback) invoked
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 24320000 bytes 255856 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 24320000. Bytes available: 255856
[2020-09-27 09:58:32] [KVS]postReadCallback(): Get Stream data returned: buffer size: 16372 written bytes: 16372 for upload handle: 6 current stream handle: 11943984
[2020-09-27 09:58:32] [KVS]postReadCallback(): Wrote 16372 bytes to Kinesis Video. Upload stream handle: 6
[2020-09-27 09:58:32] [KVS]postWriteCallback(): postBodyStreamingWriteFunc (curl callback) invoked
[2020-09-27 09:58:32] [KVS]postWriteCallback(): Curl post body write function for stream with handle: b0ee5507ef4d31b1f778e95f3b9b65c67ed26fec7b86a4531e2d8da17ad1260e and upload handle: 6 returned: {"EventType":"BUFFERING","FragmentTimecode":1603817908868,"FragmentNumber":"91343852336295232877016893920926768925129210550"}
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 34320000. Bytes available: 263518
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 34780000 bytes 263851 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 34780000. Bytes available: 263851
[2020-09-27 09:58:32] [KVS]postReadCallback(): postBodyStreamingReadFunc (curl callback) invoked
[2020-09-27 09:58:32] [KVS]postReadCallback(): Get Stream data returned: buffer size: 16372 written bytes: 16372 for upload handle: 6 current stream handle: 11943984
[2020-09-27 09:58:32] [KVS]postReadCallback(): Wrote 16372 bytes to Kinesis Video. Upload stream handle: 6
[2020-09-27 09:58:32] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179124636490, dts: 16038179124636490, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:32] [KVS]postReadCallback(): postBodyStreamingReadFunc (curl callback) invoked
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 35050000 bytes 257282 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 35050000. Bytes available: 257282
[2020-09-27 09:58:32] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179125041990, dts: 16038179125041990, duration: 0, size: 2354, trackId: 1, isKey 0
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 35490000 bytes 257615 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 35490000. Bytes available: 257615
[2020-09-27 09:58:32] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179125191910, dts: 16038179125191910, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 35900000 bytes 259982 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 35900000. Bytes available: 259982
[2020-09-27 09:58:32] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179125732350, dts: 16038179125732350, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:32] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179125907850, dts: 16038179125907850, duration: 0, size: 3906, trackId: 1, isKey 0
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 36050000 bytes 260315 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 36050000. Bytes available: 260315
[2020-09-27 09:58:32] [KVS]notifyDataAvailable(): Note data received: duration(100ns): 36590000 bytes 260648 for stream handle 6
[2020-09-27 09:58:32] [KVS]defaultStreamDataAvailableCallback(): Reported streamDataAvailable callback for stream handle 11943984. Upload handle 6. Duration available in 100ns: 36590000. Bytes available: 260648
[2020-09-27 09:58:32] [KVS]getStreamData(): Handle 6 waiting for last persisted ack with ts 16038179088680000
[2020-09-27 09:58:32] [KVS]postReadCallback(): Get Stream data returned: buffer size: 16372 written bytes: 2950 for upload handle: 6 current stream handle: 11943984
[2020-09-27 09:58:32] [KVS]postReadCallback(): Wrote 2950 bytes to Kinesis Video. Upload stream handle: 6
[2020-09-27 09:58:32] [KVS]postReadCallback(): postBodyStreamingReadFunc (curl callback) invoked
[2020-09-27 09:58:32] [KVS]postReadCallback(): Get Stream data returned: buffer size: 16372 written bytes: 0 for upload handle: 6 current stream handle: 11943984
[2020-09-27 09:58:32] [KVS]postReadCallback(): Pausing CURL read for upload handle: 6 waiting for last ack.
[2020-09-27 09:58:32] [KVS]putKinesisVideoFrame(): debug frame info pts: 16038179126093090, dts: 16038179126093090, duration: 0, size: 320, trackId: 2, isKey 0
[2020-09-27 09:58:32] [KVS]postWriteCallback(): postBodyStreamingWriteFunc (curl callback) invoked
[2020-09-27 09:58:32] [KVS]postWriteCallback(): Curl post body write function for stream with handle: b0ee5507ef4d31b1f778e95f3b9b65c67ed26fec7b86a4531e2d8da17ad1260e and upload handle: 6 returned: {"EventType":"ERROR","FragmentTimecode":1603817908868,"FragmentNumber":"91343852336295232877016893920926768925129210550","ErrorCode":"FRAMES_MISSING_FOR_TRACK","ErrorId":4011}
[2020-09-27 09:58:32] [KVS]continuousRetryStreamErrorReportHandler(): Reporting stream error. Errored timecode: 16038179088680000 Status: 0x5200007d
```

**Comment by hassanctech** [comment] 2020-10-27 17:52
These are your track1 timestamps:
16038179070632270
16038179071373550
16038179072025350
16038179072654990
16038179073358870
16038179074010830
16038179090040800
16038179090612800
16038179091413280
16038179092009150
16038179092659480
16038179093411800
16038179125041990
16038179125907850

And these are track2:
16038179070193970
16038179070602700
16038179071197420
16038179071413120
16038179071852010
16038179072203150
16038179072604730
16038179073188830
16038179073411810
16038179073867390
16038179089417390
16038179089867390
16038179090210620
16038179090621630
16038179091193840
16038179091438120
16038179091852020
16038179092202910
16038179092605650
16038179093188170
16038179093416040
16038179113829630
16038179124636490
16038179125191910
16038179125732350
16038179126093090


It looks like track2 is missing frames in the same time range

**Comment by hassanctech** [comment] 2020-10-27 17:59
It looks like it was waiting for persisted ack for this timecode: 16038179088680000, buffering ack was received but not persisting ack.

**Comment by staowyze** [comment] 2020-10-27 18:02
thank you for looking at this @hassanctech 
what are the `buffering ack` and `persisted ack`?

**Comment by hassanctech** [comment] 2020-10-27 18:13
See here:  https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_PutMedia.html#API_dataplane_PutMedia_ResponseElements

**Comment by hassanctech** [comment] 2020-10-27 18:22
It looks like one of the fragments at time code 16038179088680000 did not contain any data for one of the tracks.  It looks like for both audio and video tracks the most previously received frame is from ~ 1.5s prior.  What is your fragment length?

**Comment by hassanctech** [comment] 2020-10-27 18:23
In ms this is the deltas I see between successive frames, which seems very inconsistent:

track1:
--
74.13
65.18
62.96
70.39
65.2
1603
57.2
80.04
59.59
65.03
75.24
3163.01
86.59

track2:

40.88
--
59.47
21.57
43.89
35.11
40.16
58.41
22.3
45.55
1555
45
34.33
41.1
57.22
24.43
41.39
35.09
40.27
58.25
22.79
2041.36
1080.68
55.55
54.04
36.07

**Comment by hassanctech** [comment] 2020-10-27 18:33
16038179088680000 should be the timecode of the first key-frame (start of the fragment), so from what I see there are frames in both track1 and track2 after that time.  What is your GOP length?  Are you using key-frame fragmentation?

**Comment by MushMal** [comment] 2020-10-27 18:47
Thanks @hassanctech for the info. @staowyze please ensure you have a "stable" encoder that produces audio frames for every fragment. You have a way to print out the timestamps so you can match the timestamps to the fragments.

Needless to say, please upgrade to the latest commit. We will be cutting a new release soon

**Comment by staowyze** [comment] 2020-10-28 17:54
thank you for the analysis, very impressive, we do need to improve the timing of all the tracks.
I will leave the issue open for a couple of days, will close it once we verify the root cause.

**Comment by MushMal** [comment] 2020-10-28 18:20
Sounds good. We are thinking of removing this restriction from the ingestion path, however, this will still be an issue during the playback as most of the stock playback engines (HLS or MPEG-DASH) will block on missing frames and won't be able to make progress. There are some techniques for different players to cope with the missing frame tracks and we are investigating it but no ETA on any of the work

**Comment by MushMal** [comment] 2020-11-08 05:34
Closing this issue for now

**Closed by MushMal** 2020-11-08 05:34 UTC
Labels: Awaiting for an answer, Media Pipeline, question
