### ISSUE TITLE
[QUESTION] IOT failed 0x15000011

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-producer-c#208] opened 2021-04-06 02:32 UTC
We has similar issue https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/169 for our customers side
The failure rate about 60% and try to improve it.

For Curl perform failed with Timeout was reached, how about we modify the timeout (just not sure is possible reduce the failure)?
Also seems there may has firewall issue:
https://github.com/ropensci/rtweet/issues/229

log:
blockingCurlCall(): Curl perform failed for url https://c2dl21inrrhxl7.credentials.iot.us-west-2.amazonaws.com/role-aliases/KvsCameraIoTRoleAlias1/credentials with result Timeout was reached : Resolving timed out after 3001 milliseconds

** Logging ** 
[kvs_producer0.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/6261593/kvs_producer0.log)
 
Amazon Kinesis Video C Producer SDK version:  v1.1.1

**Comment by hassanctech** [comment] 2021-04-08 03:50
It looks like you have network issues because that endpoint cannot be reached, there are two things you can quickly try to help depending on your network, 

(1) Increase the timeout, `IOT_REQUEST_CONNECTION_TIMEOUT` maybe try 5 seconds instead of 3, here:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/cd05802945f62a8546c962cc59920e96c34663b5/src/source/Common/IotCredentialProvider.h#L11

(2) Remove `STATUS_IOT_FAILED` from the list of retry-able errors so the continuous retry logic won't be invoked from: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/4166f987c4f80af60de69adaa2e08eafcf64baf2/src/include/com/amazonaws/kinesis/video/common/Include.h#L60 

But I want to confirm the issue is with your network?  It is unable to make a connection sometimes within 3s and needs longer time?  You will need to try different values for `IOT_REQUEST_CONNECTION_TIMEOUT` to see if you can find a reasonable value which will minimize your failures.

**Comment by henryChmn** [comment] 2021-04-08 04:30
@hassanctech Thanks for your advise, I will try to traceroute endpoint when issue happen.

**Comment by henryChmn** [comment] 2021-04-13 09:39
@hassanctech 
I have done some testing for network condition tests with kvs sample code,
and found if our cameras  IOTA/ R3 test with ethernet which has a firewall problem.

KVS sample code test result:
case 1. ubuntu with Ethernet: ok
case 2. R3 with wifi: ok
case 3. R3 with Ethernet: **iot fail**
case 4. R3 with Ethernet(direct to isp): ok

for case 3 and 4 are interested why have different result.
 
blockingCurlCall(): Curl perform failed for url https://c2dl21inrrhxl7.credentials.iot.us-west-2.amazonaws.com/role-aliases/KvsCameraIoTRoleAlias1/credentials with result Timeout was reached : Resolving timed out

**Comment by hassanctech** [comment] 2021-04-26 15:24
Can you please try `nslookup` on the url when this happens to see if it will resolve and what the latency is, perhaps it's just timing out, here is our connection timeout:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/7f4ea67b667217670cd90a6bc119e11dd6f12f9b/src/source/Common/IotCredentialProvider.h#L11

**Comment by henryChmn** [comment] 2021-04-27 01:44
@hassanctech  I test it in ubuntu:
![image](https://user-images.githubusercontent.com/58592084/116172311-16112c80-a73d-11eb-8279-ce96ae1df467.png)

**Comment by henryChmn** [comment] 2021-04-27 02:59
@hassanctech When it happen:
![image](https://user-images.githubusercontent.com/58592084/116178146-9e94ca80-a747-11eb-8182-9b121dfba863.png)

**Comment by hassanctech** [comment] 2021-05-03 17:44
There's really nothing the SDK here if `curl` is having issues connecting it appears that there are issues with your network.  What happens if you increase this `IOT_REQUEST_CONNECTION_TIMEOUT ` to maybe 10s?

**Comment by henryChmn** [comment] 2021-05-04 01:16
@hassanctech I modify to 30 seconds already, but still timeout with 5 seconds, how about modify IOT_REQUEST_COMPLETION_TIMEOUT?
![image](https://user-images.githubusercontent.com/58592084/116950962-2daa6100-acb9-11eb-9488-d7e329039323.png)

**Comment by hassanctech** [comment] 2021-05-04 01:20
Yea please increase IOT_REQUEST_COMPLETION_TIMEOUT as well.

**Comment by henryChmn** [comment] 2021-05-04 11:04
@hassanctech I increase IOT_REQUEST_COMPLETION_TIMEOUT to 30 seconds still timeout with 5 seconds, don't know why.

**Comment by henryChmn** [comment] 2021-05-12 07:50
@hassanctech We want to modify curl timeout with 30 seconds for our application, could you please let me know how to configure it in SDK?

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/Common/Curl/CurlCall.c#L66-L69

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/Response.c#L183-L187

**Comment by hassanctech** [comment] 2021-08-02 14:59
@henryChmn Were you able to get past this issue?  If not can you please try with the latest SDK release 1.2.0?  We've made several fixes there which might make this issue go away.  Thank you.

**Comment by hassanctech** [comment] 2021-08-16 15:41
Closing due to no update.

**Closed by hassanctech** 2021-08-16 15:41 UTC
Labels: question
