### ISSUE TITLE
[QUESTION] Using C Library in Java via JNI and AWS Lambda

### ISSUE THREAD

**Issue by Julchenwsf** [awslabs/amazon-kinesis-video-streams-producer-c#131] opened 2020-10-30 14:09 UTC
Hello,

I build these library under an EC2 instance from "amzn-ami-hvm-2018.03.0.20181129-x86_64-gp2" which is the environment from AWS lambda. After this I try to add the resulted .so file to my aws lambda java project by including it into the Library path. But when i upload it to Lambda it says "unsatisfied Link error". Do you have an Idea why this is not working?

Best regards Julia

**Comment by hassanctech** [comment] 2020-10-30 15:35
Can you run `ldd` on the so file to see what libraries it needs to link to?  Here is an example we have using the C library in Java with JNI:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java

In particular you'll find the .so files here for various platforms: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/tree/master/src/main/resources/lib

This should help figure out how to set your so files / JNI so that all links are satisfied.

**Comment by hassanctech** [comment] 2020-10-30 15:38
Closing since this is a duplicate of an issue that was created in the CPP repo:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/598

**Closed by hassanctech** 2020-10-30 15:38 UTC
Labels: question
