### ISSUE TITLE
[QUESTION] Interleaved video

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-producer-c#210] opened 2021-04-14 04:14 UTC
Our cameras upload stream has Interleaved video problem 
I check with kvs_producer log and  timestamp from video encoder are all correctly,
Need help for this problem.
Does KVS service has any way to verify timestamp for uploaded stream ?

platform: mips
cproducer SDK version: v1.1.1
** Logging ** 
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/6308105/log.txt)

https://user-images.githubusercontent.com/58592084/114653846-81a9d180-9d1b-11eb-886f-03e10eefed9f.mp4

**Comment by henryChmn** [comment] 2021-04-15 10:02
I found when stream connection stale, the Interleaved video problem also happen,
Does this error will cause such problem?
 
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/6316970/log.txt)

https://user-images.githubusercontent.com/58592084/114851560-8ef6b700-9e14-11eb-8d0c-444d4e9fda8d.mp4


https://user-images.githubusercontent.com/58592084/114851570-90c07a80-9e14-11eb-8f7f-b45a4d409a60.mp4

**Comment by hassanctech** [comment] 2021-04-26 15:34
Can you please provide some details here, I do not see a difference between the two.  What problem are you seeing?  Which version of the SDK are you using?

In your logs I do see lots of timeouts that can cause issues.

**Comment by henryChmn** [comment] 2021-04-27 01:38
@hassanctech cproducer SDK version: v1.1.1
Video interleave problem in getClip_0402pm

**Comment by hassanctech** [comment] 2021-05-03 17:46
Again I do not see what the issue is, can you please explain this further?

**Comment by henryChmn** [comment] 2021-05-04 01:22
@hassanctech OSC timestamp shows sequence as below,
04-15-2021 04:02:25PM
04-15-2021 04:02:18PM
04-15-2021 04:02:19PM
04-15-2021 04:02:20PM
04-15-2021 04:02:18PM
04-15-2021 04:02:19PM
04-15-2021 04:02:20PM
04-15-2021 04:02:21PM

**Comment by hassanctech** [comment] 2021-05-04 01:25
What is OSC? Where are these timestamps coming from?

**Comment by henryChmn** [comment] 2021-05-04 01:29
@sorry typo, is OSD on screen display

**Comment by hassanctech** [comment] 2021-05-04 04:50
I still do not understand where is time stamp coming from.  Is it coming from the Producer SDK, or is it your encoder?  I downloaded your MP4 getClip_0402pm

And ran `ffprobe -i $filename -show_packets | grep pts_time` and this is the [result](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/6419029/result.txt) 

They are strictly monotonically increasing.  It looks like your player or something else is messing with the timecodes which results in the interleaving.

Also I do note when I diff the PTS of successive frames sometimes its 100ms sometimes in 2ms, it seems your encoder is not very consistent, which could indicate some other issues, but the interleaving is not present in the MP4 you sent me according to the dump from `ffprobe`

**Comment by henryChmn** [comment] 2021-05-04 05:52
@time stamp is coming from our encoder
look into the ffprobe detail result, video packet duration is 33ms and audio packet duration is 128ms

[PACKET]
### codec_type=video
stream_index=0
pts=0
pts_time=0.000000
dts=0
dts_time=0.000000
**duration=33**
duration_time=0.033000
convergence_duration=N/A
convergence_duration_time=N/A
size=57871
pos=3312
flags=K_
[/PACKET]
[PACKET]
### codec_type=audio
stream_index=1
pts=1
pts_time=0.001000
dts=0
dts_time=0.000000
**duration=N/A**
duration_time=N/A
convergence_duration=N/A
convergence_duration_time=N/A
size=229
pos=61183
flags=K_
[/PACKET]
[PACKET]
### codec_type=video
stream_index=0
pts=100
pts_time=0.100000
dts=100
dts_time=0.100000
**duration=33**
duration_time=0.033000
convergence_duration=N/A
convergence_duration_time=N/A
size=6626
pos=61412
flags=__
[/PACKET]
[PACKET]
### codec_type=audio
stream_index=1
pts=128
pts_time=0.128000
dts=127
dts_time=0.127000
**duration=128**
duration_time=0.128000
convergence_duration=N/A
convergence_duration_time=N/A
size=242
pos=68038
flags=K_

**Comment by henryChmn** [comment] 2021-05-04 06:24
@hassanctech aslo i check with size pattern as bleow,
seems has ghost frames

**12:size=57871**
27:size=229
42:size=6626
57:size=242
72:size=6624
87:size=256
102:size=6048
117:size=253
132:size=6153
147:size=6153
162:size=248
177:size=6130
192:size=228
207:size=6073
222:size=239
237:size=6020
252:size=244
267:size=6065
282:size=6424
297:size=249
312:size=6360
327:size=250
342:size=5961
357:size=253
372:size=5751
387:size=5762
402:size=247
417:size=5877
432:size=246
447:size=5820
462:size=249
477:size=6132
492:size=249
507:size=6204
522:size=5555
537:size=250
552:size=5903
567:size=291
582:size=5877
597:size=255
612:size=5599
627:size=6062
642:size=234
657:size=6105
672:size=241

**687:size=57871**
702:size=229
717:size=6626
732:size=242
747:size=6624
762:size=256
777:size=6048
792:size=253
807:size=6153
822:size=6153
837:size=248
852:size=6130
867:size=228
882:size=6073
897:size=239
912:size=6020
927:size=244
942:size=6065
957:size=6424
972:size=249
987:size=6360
1002:size=250
1017:size=5961
1032:size=253
1047:size=5751
1062:size=5762
1077:size=247
1092:size=5877
1107:size=246
1122:size=5820
1137:size=249
1152:size=6132
1167:size=249
1182:size=6204
1197:size=5555
1212:size=250
1227:size=5903
1242:size=291
1257:size=5877
1272:size=255
1287:size=5599
1302:size=6062
1317:size=234
1332:size=6105
1347:size=241

**1362:size=58554**
1377:size=259
1392:size=6799
1407:size=292
1422:size=6466
1437:size=6546
1452:size=329
1467:size=6192
1482:size=305
1497:size=6330
1512:size=235
1527:size=6463
1542:size=257
1557:size=6469
1572:size=6126
1587:size=239
1602:size=6828
1617:size=246
1632:size=6250
1647:size=223
1662:size=6296
1677:size=6198
1692:size=216
1707:size=6018
1722:size=274
1737:size=6516
1752:size=223
1767:size=6457
1782:size=228
1797:size=5982
1812:size=6175
1827:size=238
1842:size=5711
1857:size=228
1872:size=5545
1887:size=231
1902:size=5936
1917:size=5437
1932:size=235
1947:size=5923
1962:size=254
1977:size=6177
1992:size=259
2007:size=5992
2022:size=290

**2037:size=58554**
2052:size=259
2067:size=6799
2082:size=292
2097:size=6466
2112:size=6546
2127:size=329
2142:size=6192
2157:size=305
2172:size=6330
2187:size=235
2202:size=6463
2217:size=257
2232:size=6469
2247:size=6126
2262:size=239
2277:size=6828
2292:size=246
2307:size=6250
2322:size=223
2337:size=6296
2352:size=6198
2367:size=216
2382:size=6018
2397:size=274
2412:size=6516
2427:size=223
2442:size=6457
2457:size=228
2472:size=5982
2487:size=6175
2502:size=238
2517:size=5711
2532:size=228
2547:size=5545
2562:size=231
2577:size=5936
2592:size=5437
2607:size=235
2622:size=5923
2637:size=254
2652:size=6177
2667:size=259
2682:size=5992
2697:size=290

2712:size=58303
2727:size=6702
2742:size=256
2757:size=6560
2772:size=230
2787:size=6760
2802:size=228
2817:size=6653
2832:size=233
2847:size=6186
2862:size=6409
2877:size=244
2892:size=5851
2907:size=303
2922:size=6433
2937:size=239
2952:size=6292
2967:size=5852
2982:size=240
2997:size=6335
3012:size=246
3027:size=6124
3042:size=242
3057:size=6485
3072:size=244
3087:size=6319
3102:size=5901
3117:size=234
3132:size=6448
3147:size=238
3162:size=6437
3177:size=236
3192:size=6368
3207:size=5978
3222:size=238
3237:size=6189
3252:size=234
3267:size=5834
3282:size=244
3297:size=6041
3312:size=266
3327:size=5984
3342:size=6253
3357:size=238

**Comment by jonescx** [comment] 2021-05-04 07:39
@hassanctech This ticket is also related to the interleaving video. 
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/213

**Comment by jonescx** [comment] 2021-05-04 07:50
@hassanctech Here is another sample for interleaved video. The hand suddenly disappeared in the 6th sec of video. This problem may come from the retry-upload in the SDK when the network is not stable. Could you take a look this https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/213 ticket?

https://user-images.githubusercontent.com/6426584/116973915-d2479580-acef-11eb-9204-76f61460c3c5.mp4

**Comment by sbarryabode** [comment] 2021-05-05 14:56
@hassanctech we are using the aws sdk for javascript. We are calling getClip on KinesisVideoArchivedMedia. Here is an payload:
```json
{
  "StreamName": "example-stream-name", 
  "ClipFragmentSelector": {
    "FragmentSelectorType": "PRODUCER_TIMESTAMP",
    "TimestampRange": { 
      "EndTimestamp": 1619665199,
      "StartTimestamp": 1619665229
    }
  }
}
```

**Comment by disa6302** [comment] 2022-04-25 00:26
Your start timestamp seems to be greater than the EndTimestamp? This would be fine if you were using SERVER_TIMESTAMP. But with PRODUCER_TIMESTAMP, End timestamp must be greater than start timestamp.

Check this documentation: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_ClipTimestampRange.html#KinesisVideo-Type-reader_ClipTimestampRange-EndTimestamp

Closing this now. Feel free to reopen if you are still facing issues here.

**Closed by disa6302** 2022-04-25 00:26 UTC
Labels: question
