### ISSUE TITLE
G711 audio format sample and test guide.

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/amazon-kinesis-video-streams-producer-c#230] opened 2021-07-29 11:37 UTC
I try to finalize a audio&video sample with G711 audio format:
https://github.com/awsa2ron/amazon-kinesis-video-streams-producer-c/tree/g711-alaw

putMedia succeeded, but playback failed, either aws console nor test page. 
Error is:
```
AAC CPD must be of length 2 or 5, but was 18."
```

**Comment by disa6302** [comment] 2021-08-03 16:00
Closing this as duplicate of #229

**Closed by disa6302** 2021-08-03 16:00 UTC
Labels: enhancement
