### ISSUE TITLE
[QUESTION] Dealing with frame rate, PTS, DTS and duration?

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-producer-c#284] opened 2022-02-18 16:15 UTC
I'm connecting to an Axis M1135 camera which gives me Opus/H264 over RTP. I'm using GStreamer to setup a pipeline and forward the received data using `putKinesisVideoFrame()` whenever a new sample becomes available. There are a couple of things I'm not sure about how to handle correctly.

**How to deal with durations?**

GStreamer delivers `GstBuffer` instances with a `pts`, `dts` and `duration`.  The `GstBuffer::duration` field always has a fixed value of 40ms. When I measure the difference between video frames, in my sink callback, the duration varies between 39-41ms. I've also used `ffprobe` to measure the difference between packets and ffprobe gives me durations that vary between 36ms-39ms. I haven't found a reason why there is this difference between durations between GStreamer and ffprobe.  Currently I'm setting `Frame::duration` to 0, which doesn't seem to have any impact on the playback. I'm using the player from the AWS Kinesis Video Streams console.  Is it ok to set duration to 0?

**How to deal with timestamps**

My application will receive media packets (rtp) continuously and I'll sent them to KVS. There might be situations where the RTP gets interrupted/restarted.  Currently I'm using relative timestamps, but from [this](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/timestamps.md#producer-and-service-side-timestamp-indexing) documentation I think this is not the best option.

> usage of the relative timestamps in the SDK is discouraged due to unanticipated side-effects with the producer time codes in the stream jumping back on each session (as they start from 0) and only very specific applications would need this behavior.

When I want to use absolute timestamps I could remember the time that I recdeive the first RTP packet, then add the `GstBuffer::pts` value (which I think is relative). Would it make sense to use this approach?

**StreamCaps.frameRate and StreamMetrics.currentFrameRate**

I'm testing this application on a intel i7 PC but also on a RPI. When I use the same camera, same code I'm seeing a `currentFrameRate` value from ~100-200  on the RPI. On my PC the value is stable around 25 (which is the FPS that I've configured on the Axis camera).  Any ideas why these values differ so much?  I assume this is the calculated frame rate at which the frames are received by this SDK?  I did see that the default `StreamCaps.frameRate` value is set to 120.Though the samples don't change this value neither but do use 25 FPS to update the pts values and set the duration.

**Comment by MushMal** [comment] 2022-02-18 20:10
You can ignore the duration in this case and specify 0. Regarding the timestamps. I recommend not using relative timestamps but use absolute timestamps for almost all cases. The important question to ask is whether your media pipeline is "stable" - that means whether it's producing frames at a regular cadence rather than in bursts. If it's stable enough, you could use the system clock - as long as it is always monotonically increasing. There is no worry about the stamp overlap between the reboots as those would require new streaming sessions so it's OK.

Try to select the frame rate in the StreamCaps as close to the real thing as possible - this is primarily used for optimizing the content view buffers (not content store). The StreaamMetrics.currentFrameRate is what the client actually observes as the running frame rate. There are some documents highlighting the structures in the cpp repo.

Regarding the high frame rate in the metrics. The issue is that the frame rate is calculated given a period of time (don't remember the details). So, if you have a bursty media pipeline and frames would be "clumped" together then it would appear as for that period of time there is a very high frame rate. The SDK is using exponential mean calculation to average out the running values so in stable conditions it would reflect the actual intended frame rate as observed.

**Comment by disa6302** [comment] 2022-02-18 22:47
Closing since this question is answered. Feel free to reach out if you have more questions.

**Closed by disa6302** 2022-02-18 22:47 UTC
Labels: question
