### ISSUE TITLE
[QUESTION] Why sometimes the putKinesisVideoFrame api takes a long time

### ISSUE THREAD

**Issue by liuxin888888** [awslabs/amazon-kinesis-video-streams-producer-c#315] opened 2022-07-18 14:20 UTC
**Media Pipeline:**
    Audio and Video streaming
    STREAMING_TYPE_REALTIME
**Describe the issue:**
    Sometimes this function only takes tens of microseconds, and sometimes it takes tens or even hundreds of milliseconds.   Is it expected? What could be reason for the delay?  
    Our product has multiple cameras, and we plan to upload 6 or more KVS streams at the same time, so we don't want this API to block and cause the data to not be sent in time (at least to allow the data to have a chance to be written into the kvs buffer)

**Comment by liuxin888888** [comment] 2022-07-19 09:34
hi,
@hassanctech @MushMal 
Thank you very much for your replies, the SDK version I am using is 1.3.0, I can understand that uploading multiple streams at the same time leads to a longer delay, but I have also tested uploading only a single video stream (no audio track), although Most of the time it returns fast, but occasionally it still blocks for tens of milliseconds. I want to know what will affect its blocking time, is it related to the network congestion and the size of the uploaded data?

**Comment by MushMal** [comment] 2022-07-19 17:19
I would recommend superimposing the pauses against the verbose logs by printing out a line when the delay is larger than some threshold. This can give you some idea what's going on at the time of the "pause". As I mentioned, the likely culprit is the stream state machine transitions like auth integration or issuing a call to a backend API

**Comment by liuxin888888** [comment] 2022-07-21 10:18
Using the above method in the putFrame function to test, the functions that run for more than 10ms will be recorded. I found that the following two functions in the putFrame function are often recorded (the frequency is about 1 time per second). What could be the reason?

`        // Get the size of the packaged frame
        CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, NULL, &packagedSize, &encodedFrameInfo));`
`        // Actually package the bits in the storage
        CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, pAlloc, &packagedSize, &encodedFrameInfo));`

**Comment by liuxin888888** [comment] 2022-07-21 10:20
Using the above method in the putFrame function to test, the functions that run for more than 10ms will be recorded. I found that the following two functions in the putFrame function are often recorded (the frequency is about 1 time per second). What could be the reason?

`CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, NULL, &packagedSize, &encodedFrameInfo));`
`CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, pAlloc, &packagedSize, &encodedFrameInfo));`

**Comment by liuxin888888** [comment] 2022-07-21 10:26
Using the above method in the putFrame function to test, the functions that run for more than 10ms will be recorded. I found that the following two functions in the putFrame function are often recorded (the frequency is about 1 time per second). What could be the reason?

`        // Get the size of the packaged frame
        CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, NULL, &packagedSize, &encodedFrameInfo)); `
`        // Actually package the bits in the storage
        CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, pAlloc, &packagedSize, &encodedFrameInfo));`

**Comment by liuxin888888** [comment] 2022-07-21 10:27
Using the above method in the putFrame function to test, the functions that run for more than 10ms will be recorded. I found that the following two functions in the putFrame function are often recorded (the frequency is about 1 time per second). What could be the reason?

// Get the size of the packaged frame 
CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, NULL, &packagedSize, &encodedFrameInfo));
// Actually package the bits in the storage 
CHK_STATUS(mkvgenPackageFrame(pKinesisVideoStream->pMkvGenerator, pFrame, pTrackInfo, pAlloc, &packagedSize, &encodedFrameInfo));

**Comment by MushMal** [comment] 2022-07-21 17:37
This function is packaging the frame bits into MKV streamable format so it will be called per frame at least twice - once to get the required size and the second time to actually package the frame. These should take nanoseconds. 

It's really hard to pinpoint these sorts of stales in a running platform - there could be SDK related just as I mentioned when the SDK calls auth integration or tries to make a backend call OR it could be something in the platform happening in the background which is out of SDK control.

**Comment by liuxin888888** [comment] 2022-07-22 12:54
I use the same method to run the KvsVideoOnlyStreamingSample demo in docker. The above mkv function also occasionally takes 1-5 milliseconds, Is it expected?

**Comment by MushMal** [comment] 2022-07-22 17:54
This function is defined at https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/c8325887faa3a4a296c4367b281c778be69875b6/src/mkvgen/src/MkvGenerator.c#L214

The entire body of the function is "prompt" and should run within a single thread quanta. What you are observing is likely caused by a context switch in the OS scheduler or the Docker runtime is causing some sort of a pause. Sorry, there really isn't much I can help you without trace profiling, etc... When you run the trace profiler, make sure you are on a bare metal and there are no competing background tasks/processes

**Comment by disa6302** [comment] 2022-09-26 00:10
@liuxin888888 ,

We have a new version (1.4.0) released recently which has some improvements  and bug fixes that might be useful. Please upgrade and let us know if the issue persists. Closing this for now.

**Closed by disa6302** 2022-09-26 00:10 UTC
Labels: question
