### ISSUE TITLE
[QUESTION] Need to send overlapped video clips to KVS

### ISSUE THREAD

**Issue by pwijeratne** [awslabs/amazon-kinesis-video-streams-producer-c#154] opened 2020-12-18 22:21 UTC
Need to send video clips that has overlapped fragments with the previous video clip sent

I am utilizing the C Producer Library. The scenario is as follows:
1. upload a video clip
2. upload a second video clip immediately after the previous one. Since this clip has to start from an iframe, I seek a few frames in the past in a buffer to get to the iframe and it might be overlapped with the previous clip sent. In other words, this iframe and a few frames after that may have uploaded at the end of the previous video clip.

I can seek forward to the next iframe and I will not get this error, but I will loose video capture doing so.

** Logging ** 
[ERROR]: [18/12-13:03:13.359][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x32000002
[ERROR]: [18/12-13:03:13.359][KVS_APP][kvs_module.c::716][716]seq=36506 frame size=11067 time=1608325390503313
[ERROR]: [18/12-13:03:13.372][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x32000002
[ERROR]: [18/12-13:03:13.373][KVS_APP][kvs_module.c::716][716]seq=36507 frame size=4647 time=1608325390570501
[ERROR]: [18/12-13:03:13.381][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x32000002
[ERROR]: [18/12-13:03:13.381][KVS_APP][kvs_module.c::716][716]seq=36508 frame size=8470 time=1608325390630751
[ERROR]: [18/12-13:03:13.394][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x32000002
[ERROR]: [18/12-13:03:13.394][KVS_APP][kvs_module.c::716][716]seq=36509 frame size=6207 time=1608325390711817
[ERROR]: [18/12-13:03:13.408][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x32000002
[ERROR]: [18/12-13:03:13.408][KVS_APP][kvs_module.c::716][716]seq=36510 frame size=8570 time=1608325390781457
[ERROR]: [18/12-13:03:13.662][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x30000005
[ERROR]: [18/12-13:03:13.680][KVS_APP][kvs_module.c::716][716]seq=36511 frame size=102186 time=1608325390840505
[ERROR]: [18/12-13:03:13.697][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x30000005
[ERROR]: [18/12-13:03:13.697][KVS_APP][kvs_module.c::716][716]seq=36512 frame size=5906 time=1608325390913945
[ERROR]: [18/12-13:03:13.712][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x30000005
[ERROR]: [18/12-13:03:13.712][KVS_APP][kvs_module.c::716][716]seq=36513 frame size=4260 time=1608325390973318
[ERROR]: [18/12-13:03:13.726][KVS_APP][kvs_module.c::714][KVS] putFrame video failed with 0x30000005
[ERROR]: [18/12-13:03:13.726][KVS_APP][kvs_module.c::716][716]seq=36514 frame size=3178 time=1608325391039516

**Comment by MushMal** [comment] 2020-12-18 22:31
* Assuming you are using an intermittent producer scenario with create stream/stream/stopSync/free and repeat for the next clip, you don't need to skip the first non-key-frames. The code will skip the initial non-key-frames automatically.
* You are getting error 0x32000002 (STATUS_MKV_INVALID_FRAME_TIMESTAMP)which indicates that your timestamp is older than the previous fragment timestamp. This is by design. Use the intermittent scenario like above with terminating and freeing the previous stream or you need to either skip these overlapped frames or just let them fail?
* Same issue is with 0x30000005 (STATUS_CONTENT_VIEW_INVALID_TIMESTAMP). This indicates that the frames being produced have older timestamps.

**Comment by pwijeratne** [comment] 2020-12-21 18:54
If I "let them fail" as your last suggestion, would there be any consequences other than just seeing the error call backs? In other words, can I just assume this error as a warning?

**Comment by MushMal** [comment] 2020-12-21 19:01
It would depend on your application. If your application needs those frames then it would have an impact. If your application does not require those frames then it would be OK.

As we are not exposed to your application, we can't give you any recommendation. Try to experiment and see what your scenario needs. 

There is a low-level dev documentation available here that might help too: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/tree/master/docs

**Comment by disa6302** [comment] 2020-12-23 17:21
Closing since question is answered

**Closed by disa6302** 2020-12-23 17:21 UTC
Labels: Assumed Answered, question
